---
title: "Gathering and receiving feedback"
categories: [Ending a project] ## Current categories are: Beginning a project, During a project, Ending a project, General (Categories are case sensitive)
date: "11.13.2024" ## date and time format is MM.DD.YYYY
author: Niko Laurila ## Author/authors of the article. 
date-modified: last-modified ## This adds an automatic last modified field to the article, last-modified function will automatically add the correct date when a modification is made to the article.
toc: true ##this adds an automatic Table-Of-Content for your article.
---

# Process of gathering feedback

After you have completed a project it's time to start looking for improvements for the future! We encourage the process of collecting and learning from all feedback, this ensures that you always keep improving as a developer. The general process of gathering feedback is mainly split in three different parts.

1.  **Self reflection:** Koodariverstas will ask you to write your own honest thoughts about the work you have done. Mainly we want to get you to think about your future aspects and goals. How did you feel during the process, was there something you liked than you expected or disliked more than expected. What thoughts came up during your work? Would you see yourself doing the same kind of work in the future? What was especially challenging in your work? What did you find the easiest? These questions are strictly for your self improvement, and will not affect your certificates or recommendations. **This information is not shared to the company you worked with.**
2.  **Company feedback:** Koodariverstas will gather feedback from the company you worked with. This information is related to your overall performance from the company's perspective. This information will help Koodariverstas understand the overall quality and amount of work done. The company is also asked to provide their honest thoughts about your work ethics and commitment. This information will help us solve any disparities of problems between you and the company you worked with. **This information is shared between all three parties in the case where major disparities between both parties are discovered.**
3.  **Process feedback:** This feedback is purely internal to Koodariverstas and is used to improve our practices and methods. This information is gathered from you and the company you worked for. This information includes feedback on processes, guidance, management and ease of communication. **This information is not relevant to anyone else outside Koodariverstas since it's purely used for improving the core workflow of Koodariverstas**

# Process of reflecting on feedback

After all the relevant feedback (Positive and Negative) has been gathered it's time to start reflecting on the feedback received. Sometimes the feedback might be overly positive or overly negative without any real constructive elements to it. In those cases it's best to think about the reasons why this feedback was written and not over analyze the feedback itself.

Easiest way reflect on feedback given is to sum everything up into a document with all the positives and negatives listed. This makes it easier to get a full picture of work done.

Don't get stuck thinking that only perfection is acceptable, because that isn't simply true. We live in a imperfect world filled with imperfect people, everyone has their own strengths and weaknesses.

These are some of the methods you can use when combing through feedback you have received.

-   If the feedback consists of more positive aspects than negative it's best to focus more on the negative aspects when reflecting for the future. Finding out that you did a mostly good job with some improvements is a great position to be in. It lets you focus on being even better by reducing the negative points in the future.

-   If the majority of the feedback received is negative with a few positives. It's best to focus on what you did well and find ways to implement your positive traits to your negative traits. For example if you got a positive mark for pure coding and technical implementation but negative marks on reporting your work and readability of your code, you could try to start implementing more detailed comments to your code itself and writing your reports based of the comments you already made in the code.

*This article is under construction. Awaiting for more content*